### ISSUE TITLE
Handling pose jumps from loop closures

### ISSUE THREAD

**Issue by mhkabir** [srv/stereo_slam#1]
Hey guys,

If one uses the corrected odometry output for vehicle control, how would the pose output behave on loop closures? I guess there would be a jump if there graph correction is done starting from the previous nodes ?

Or is the correction applied from the front nodes, thus only affecting the older graph points and there is no odometry jump?

Kabir

**Comment by plnegre** [comment]
Hey Kabir,

yes, the corrected odometry jumps when a correction is applied to the graph. So, if you have to use the corrected odometry as an input of your control system, a filter would be desirable...

I would like to include this filter into the stereo_slam, future work ;)

Pepllu

**Comment by plnegre** [comment]
This has finally included in the commit 2a8a8327b86fcac4d46158cb97b62ef03bd55e9d
