### ISSUE TITLE
collector node.

### ISSUE THREAD

**Issue by lakid** [srv/stereo_slam#2]
Hello! Thanks for the code. 

Has the `collector` node that is launched by the demo been deprecated?

If so are there any pointcloud collector/ publishers that you might recommend?

**Comment by plnegre** [comment]
Hello @lakid, the collector node is currently deprecated. But you can save the corresponding pointcloud of every graph node by setting the parameter 'save_clouds' to true. Moreover, I'm currently working on the indigo-devel branch to develop an online reconstruction node. Not finished yet...
