### ISSUE TITLE
libhaloc error while compilling

### ISSUE THREAD

**Issue by AndreV84** [srv/stereo_slam#5]
Project 'stereo_slam' tried to find library 'haloc'.  The library is
  neither a target nor built/installed properly.  Did you compile project
  'libhaloc'? Did you find_package() it before the subdirectory containing
  its code is included?
Call Stack (most recent call first):
  CMakeLists.txt:33 (find_package)

**Comment by AjayNandoriya** [comment]
I was able to solve this error by cloning "libhaloc"  (https://github.com/srv/libhaloc) in my ROS workspace directory. But I am stuck at another error as below.
catkin_ws/src/stereo_slam/include/loop_closing.h:15:25: fatal error: libhaloc/lc.h: No such file or directory

It seems libhaloc current code version is kinetic but it needs indigo version.

**Comment by jake3991** [comment]
Having the same issue, was there any resolution?
