### ISSUE TITLE
Camera Calibration

### ISSUE THREAD

**Issue by jake3991** [srv/stereo_slam#6]
This is a great package, thanks for publishing your code!  I'm having a little bit of trouble with camera calibration though.  Right now I am calibrating the camera in the water (onboard the ROV) using the ROS camera calibration system.  It's still providing very poor results, do you have a recommended method for properly calibrating a stereo array to utilize this package?  Thanks again.

**Comment by ferreram** [comment]
For camera calibration I would advise you to use the Kalibr toolbox : https://github.com/ethz-asl/kalibr.  It should give you good results.

**Comment by jake3991** [comment]
Great thanks! Do you recommend calibrating in water or out of water?

**Comment by ferreram** [comment]
You should calibrate in water.  Otherwise you won't estimate the optical effect of the water medium on the image formation (intrinsic parameters + distortion).

**Comment by jake3991** [comment]
Great thank you!
